<?php

/**
 * @file
 * Web service client examples module.
 */

/**
 * Implements hook_commerce_checkout_page_info().
 */
function envision_wsclient_commerce_checkout_page_info() {
  $checkout_pages = array();

  $checkout_pages['checkout_to_webservice'] = array(
    'name' => t('checkout to webservice'),
    'title' => t('Connect to remote server'),
    'weight' => 5,
    'status_cart' => TRUE,
    'buttons' => TRUE,
  );

  return $checkout_pages;
}



/**
 * Implements hook_menu().
 */
function envision_wsclient_menu() {
  $items['test/restful'] = array(
    'page callback' => 'exec_wsclient',
    'file' => 'envision_wsclient.test.inc',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_default_wsclient_service().
 */
function envision_wsclient_default_wsclient_service() {

  $service = new WSClientServiceDescription();
  $service->name = 'envision_creagevapp';
  $service->label = 'Envision creagevApp';
  $service->url = 'http://218.4.19.204:8081/envision/restful/';
  $service->type = 'rest';

  // Add info about the REST service, which the user has to provide via the UI.
  $service->datatypes = array(
    'return_result' => array(
      'label' => 'Return Result',
      'property info' => array(
        'responseData' => array(
          'type' => 'text',
          'label' => 'Return Result'
        ),
      ),
    ),
  );
  
  $operation['label'] = 'Create';
  $operation['url'] = 'createvApp';
  $operation['parameter']['serviceName'] = array('type' => 'text', 'label' => 'ServiceName');
  $operation['type']='POST';


  $service->operations['create'] = $operation;
  $services[$service->name] = $service;
  //debug($service);
  
  //test
    $service = new WSClientServiceDescription();
  $service->name = 'test';
  $service->label = 'Test';
  $service->url = 'http://127.0.0.1/commerce_kickstart/test/';
  $service->type = 'rest';

  // Add info about the REST service, which the user has to provide via the UI.
  $service->datatypes = array(
    'return_result' => array(
      'label' => 'Return Result',
      'property info' => array(
        'responseData' => array(
          'type' => 'text',
          'label' => 'Return Result'
        ),
      ),
    ),
  );
  
  $operation['label'] = 'Test';
  $operation['url'] = 'restfulserver';
  $operation['parameter']['serviceName'] = array('type' => 'text', 'label' => 'ServiceName');
  $service->operations['create'] = $operation;
  $services[$service->name] = $service;
  //test end
  
  return $services;
}
